### ISSUE TITLE
local file links don't work

### ISSUE THREAD

**Issue by atomGit** [muerwre/markdown-home-tab#4]
local links, such as `file:///index.html`, don't load - the link points to `javascript:void(0)`

**Comment by atomGit** [comment]
~~this may have been caused by an issue on my end - sorry~~

nope - local links do not work it seems

browser console when clicking a local link:

`Content-Security-Policy: The page’s settings blocked an inline script (script-src-elem) from being executed because it violates the following directive: “script-src 'self' 'wasm-unsafe-eval'”
Source: javascript:void(0)`

mht 0.0.6

**Comment by muerwre** [comment]
It's the way remark parses links for some reason. Tried to use plugins like https://www.npmjs.com/package/@doist/remark-application-links, but it doesn't work.

Closing as won't fix for now.
