### ISSUE TITLE
theme changes revert

### ISSUE THREAD

**Issue by atomGit** [muerwre/markdown-home-tab#5]
there's some weirdness when making changes to a theme - using the 'dark' theme as an example, i can change the background color and the change is saved, but if i reopen the settings UI and then make another change, such as changing the link color, then the background color reverts to the default when clicking 'ok'

mht 0.0.6
ff 131

**Comment by muerwre** [comment]
Yeah, also noticed that. Gotta fix soon.

**Comment by muerwre** [comment]
Fixed it in 0.0.7, please comment if something's still wrong. Thanks for report, @atomGit!
